//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodMap.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliaco
    {
        public int id { get; set; }
        public System.DateTime datahora { get; set; }
        public int matricula { get; set; }
        public string nomeCantina { get; set; }
        public string produto { get; set; }
        public string comentario { get; set; }
        public Nullable<float> precoAtual { get; set; }
        public int nota { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Cantina Cantina { get; set; }
        public virtual Produto Produto1 { get; set; }
    }
}
