//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodMap.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cantina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cantina()
        {
            this.Avaliacoes = new HashSet<Avaliaco>();
        }
    
        public int id { get; set; }
        public string nomeCantina { get; set; }
        public string predio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avaliaco> Avaliacoes { get; set; }
    }
}
